### PR TITLE
Rs032

### PR DESCRIPTION
**Pull request by jacquems**
This update find automatically the classes that contains the main function in order to start the analysis. This branch does not have the last master update because the current master gives me an error.

### CODE REVIEW

**Comment by sgioia9** [comment]
Your second commit somehow rewrote the entire project.

**Comment by jacquems** [comment]
I only change two classes: StartAnalysisDialog and JavaDomUtils, also add one new:MainClassSearchDialog. The problem is that I was working on the branch I made 3 days ago and I could not do the merge today because the current master gives me error.

**Comment by jacquems** [comment]
I do not understand, how did I rewrite the entire project? I have only worked in the classes that I tell you. You can not merge only those three classes?

**Comment by sgioia9** [comment]
In commit https://github.com/JSwingRipples2016/jswingripples/pull/66/commits/a654463832b1ab82447d4fefb928089b844cb29b a lot of files were included.

**Comment by jacquems** [comment]
I did some change in the files: StartAnalysisDialog.java, JavaDomUtils,  and MainClassSearchDialo. Can you merge only theses classes?

**Comment by sgioia9** [comment]
Do this, please;

1. Download a brand new master branch.
2. Create a new branch.
3. Copy over the files you changed.
4. Commit.
5. Push the new branch.
6. Create a new PR.

**Pull request closed without merging**
