### PR TITLE
Show option "open with IDE"

### PR DESCRIPTION
**Pull request by jacquems**
By right-clicking on a class or item of it, the option "Open with IDE" is displayed. Currently it is unavailable, because it hasn`t implemented yet.

### CODE REVIEW

**Comment by sgioia9** [comment]
You only pushed `OpenWithIDEAction.java`. Is there something missing?

**Comment by jacquems** [comment]
Is this for now!

opencodeide

**Comment by sgioia9** [comment]
Push your latest changes to the branch!

**Comment by jacquems** [comment]
I do this last night. I will do it again.

**Comment by jacquems** [comment]
Done

**Pull request merged**
